import Head from "next/head";
import { useMemo, useState } from "react";
import {
  AnimatedAxis,
  AnimatedBarSeries,
  buildChartTheme,
  Tooltip,
  XYChart,
} from "@visx/xychart";
import Link from "../components/Home/Link";
import experience from "../experience.json";
import { techonologyByTime } from "../utils/experienceByTechnology";

const customTheme = buildChartTheme({
  colors: ["#99F6E4"],
  svgLabelSmall: {
    className: "font-sans text-sm fill-current text-white",
    verticalAnchor: "middle",
  },
  xAxisLineStyles: {
    strokeWidth: 1,
    stroke: "#818CF8",
  },
  xTickLineStyles: {
    strokeWidth: 1,
    stroke: "#818CF8",
  },
});

const accessors = {
  xAccessor: (d) => d.technology,
  yAccessor: (d) => d.time,
};

export default function Home() {
  const [unit, setUnit] = useState("years");
  const data = useMemo(() => techonologyByTime(experience, unit), [unit]);

  return (
    <div>
      <Head>
        <title>Alejandro González - Full Stack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="fixed top-0 left-0 flex h-screen w-64 flex-col justify-between">
        {/* <h2 className="text-slate-50 text-2xl font-bold mx-auto bg-indigo-600 text-center p-4">
          Alejandro González
        </h2> */}
        <h2 className="text-center">Alejandro González</h2>
        <ul className="space-y-4 p-8">
          <li>
            <Link href="/experience">Experience</Link>
          </li>
          <li>
            <Link href="/something">Something</Link>
          </li>
          <li>
            <Link href="/whatever">Whatever</Link>
          </li>
        </ul>
        <div>Ways of contacting me</div>
      </div>

      <main className="ml-64 min-h-screen bg-gradient-to-b from-teal-200 to-indigo-500">
        <div className="grid grid-cols-4 p-32 text-lg">
          <div className="p-4">
            I am a passionate software developer with 11 years of experience.
          </div>

          <p className="p-4">
            I can create top-notch web applications,{" "}
            <strong>like this one</strong>, and take care of feature delivery
            from design to deploy in a completely autonomous way.
          </p>

          <p className="p-4">
            I can design and build cloud infrastructure and automated
            deployments.
          </p>

          <p className="p-4">
            In a nutshell, I can lead software projects and deliver with
            quality.
          </p>
        </div>
        <div className="p-4">
          <select>
            {["Years", "Months", "Working Days", "Working Hours"].map(
              (unit) => (
                <option
                  key={unit}
                  onClick={() =>
                    setUnit(unit.replace("Working ", "").toLowerCase())
                  }
                >
                  {unit}
                </option>
              )
            )}
          </select>
        </div>
        <div className="overflow-x-auto">
          <XYChart
            height={480}
            width={data.length * 100}
            xScale={{ type: "band", padding: 0.3 }}
            yScale={{ type: "linear" }}
            margin={{ left: 0, right: 0, top: 0, bottom: 48 }}
            theme={customTheme}
          >
            <AnimatedAxis orientation="bottom" numTicks={data.length} />
            <AnimatedBarSeries
              dataKey={`Experience in ${unit}`}
              data={data}
              radius={8}
              radiusTop
              xAccessor={accessors.xAccessor}
              yAccessor={accessors.yAccessor}
            />
            <Tooltip
              snapTooltipToDatumX
              snapTooltipToDatumY
              renderTooltip={({ tooltipData }) => (
                <div className="text-base font-normal">
                  <div className="text-indigo-500">
                    {accessors.xAccessor(tooltipData.nearestDatum.datum)}
                  </div>
                  <div>
                    <strong>
                      {accessors.yAccessor(tooltipData.nearestDatum.datum)}
                    </strong>
                    {` ${unit}`}
                  </div>
                </div>
              )}
            />
          </XYChart>
        </div>
      </main>
    </div>
  );
}
